project:
  title: "published-202505-ferte-reservoirnet"
  render:
    - main.qmd
    - README.qmd
status: published

title: "Reservoir Computing in R: a Tutorial for Using reservoirnet to Predict Complex Time-Series"
author:
  - name: Thomas Ferté
    corresponding: false
    orcid: 0000-0001-8455-4665
    affiliations:
      - name: Inserm, Inria
        department: Univ. Bordeaux, INSERM, INRIA SISTM, BPH, U1219, F-33000 Bordeaux, France
      - name: CHU de Bordeaux
        department: "Bordeaux Hospital University Center, Pôle de santé publique, Service d'information médicale, F-33000 Bordeaux, France"
  - name: Kalidou Ba
    corresponding: false
    orcid: 0000-0001-6552-265X
    affiliations:
      - name: Inserm, Inria
        department: Univ. Bordeaux, INSERM, INRIA SISTM, BPH, U1219, F-33000 Bordeaux, France
  - name: Dan Dutartre
    corresponding: false
    orcid: 0000-0001-8210-461X
    affiliations:
      - name: Inria
        department: INRIA, F-33000 Bordeaux, France
  - name: Pierrick Legrand
    corresponding: false
    affiliations:
      - name: Bordeaux INP
        department: ENSC, 109 avenue Roul, 33400, Talence France
      - name: Inria
        department: INRIA, F-33000 Bordeaux, France
      - name: IMS
        department: IMS, UMR CNRS 5218
  - name: Vianney Jouhet
    corresponding: false
    orcid: 0000-0001-5272-2265
    affiliations:
      - name: Inserm
        department: Inserm Bordeaux Population Health Research Center UMR 1219, team AHeaD, F-33000 Bordeaux
      - name: CHU de Bordeaux
        department: "Bordeaux Hospital University Center, Pôle de santé publique, Service d'information médicale, F-33000 Bordeaux, France"
  - name: Rodolphe Thiébaut
    corresponding: false
    orcid: 0000-0002-5235-3962
    affiliations:
      - name: Inserm, Inria
        department: Univ. Bordeaux, INSERM, INRIA, BPH, U1219, F-33000 Bordeaux, France
      - name: CHU de Bordeaux
        department: "Bordeaux Hospital University Center, Pôle de santé publique, Service d'information médicale, F-33000 Bordeaux, France"
  - name: Xavier Hinaut
    corresponding: false
    orcid: 0000-0002-1924-1184
    affiliations:
      - name: Inria
        department: INRIA, F-33000 Bordeaux, France
      - name: IMN
        department: Univ. Bordeaux, CNRS, IMN, UMR 5293, Bordeaux, France
      - name: LaBRI
        department: LaBRI, Univ. Bordeaux, Bordeaux INP, CNRS UMR 5800.
  - name: Boris P Hejblum
    email: boris.hejblum@u-bordeaux.fr
    corresponding: true
    orcid: 0000-0003-0646-452X
    affiliations:
      - name: Inserm, Inria
        department: Univ. Bordeaux, INSERM, INRIA SISTM, BPH, U1219, F-33000 Bordeaux, France
date: 2025-06-27
abstract: >+
  Reservoir Computing (RC) is a machine learning method based on neural networks that efficiently process information generated by dynamical systems. It has been successful in solving various tasks including time series forecasting, language processing or voice processing. RC is implemented in `Python` and `Julia` but not in `R`. This article introduces `reservoirnet`, an `R` package providing access to the `Python` API `ReservoirPy`, allowing `R` users to harness the power of reservoir computing. This article provides an introduction to the fundamentals of RC and showcases its real-world applicability through three distinct sections. First, we cover the foundational concepts of RC, setting the stage for understanding its capabilities. Next, we delve into the practical usage of `reservoirnet` through two illustrative examples. These examples demonstrate how it can be applied to real-world problems, specifically, regression of COVID-19 hospitalizations and classification of Japanese vowels. Finally, we present a comprehensive analysis of a real-world application of `reservoirnet`, where it was used to forecast COVID-19 hospitalizations at Bordeaux University Hospital using public data and electronic health records.
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/arxn-6z34"
  publisher: "French Statistical Society"
  issn: "2824-7795"
  url: "https://computo-journal.org/published-202505-ferte-reservoirnet/"
  pdf-url: "https://computo-journal.org/published-202505-ferte-reservoirnet/main.pdf"
  issued: "2025-06-27"
google-scholar: true
related-identifiers:
  - relation: IsVersionOf
    type: URL
    identifier: "https://hal.science/hal-05208084v1"
github-user: computorg
repo: "published-202505-ferte-reservoirnet"
date-modified: last-modified
keywords: [Reservoir Computing, Covid-19, Electronic Health Records, Time series]
bibliography: references.bib
format:
  computo-html: default
  computo-pdf: 
    echo: true
    tidy: styler
