name: ferte
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openssl
  - numpy
  - pandas
  - scipy
  - dill
  - joblib
  - tqdm
  - tenacity
  - plotly
  - python-dateutil
  - six
  - tzdata
  - pytz
  - packaging
  - pip:
   - reservoirpy
